import React from 'react'
import "../css/TermsAndCondition.css";
import Image from "../Assets/Images/Vector.svg";

const TermsAndCondition = () => {
  return (
    <div>
        <div className="container-fluid mainTermsAndCondition">
          <img src={Image} alt="backimg" className='backgroundImgTermsAndConditionpage' />
            <div className="container">
                <div className="row">
                    <div className="col-lg-7 my-4">
                      <h6 className='termsandcontionTitle'>TERMS AND AGREEMENTS</h6>
                      <h1 className='termsandcontionHeading my-5'>Terms headline goes here</h1>
                      <p className='termsandconditionPera'>Neque, nisl penatibus sed morbi arcu. Fermentum dui elit sollicitudin convallis nibh quis malesuada sit sit. Mus elit rhoncus eu eget a pharetra interdum. Vivamus amet, diam lacus, quam vulputate consectetur sit velit eget. Vulputate tempus lorem consequat nunc tristique porttitor odio. Amet tempus.</p>
                    </div>
                    <div className="col-lg-12 TermsAndConditionDetailText">
                        <p className='termsandconditionUpdateDate'>Last updated on April 17, 2021</p>
                        
                        <p className="termsandconditiontxt">
                             Condimentum vitae metus, hendrerit faucibus platea proin convallis fermentum. Id lectus morbi tincidunt ultrices. Amet, vulputate risus tempor velit consectetur pulvinar arcu tincidunt diam. Auctor eu consectetur tristique tincidunt proin condimentum massa magna. Ut purus ut turpis sed.
                        </p>

                        <p classname="termsandconditiontxt">Integer scelerisque risus cursus nam lacus molestie tellus. Neque in euismod nunc enim eu. Adipiscing egestas velit eget erat. Est netus aliquam, risus duis. Platea phasellus ac id pulvinar proin eu, sollicitudin tempor.</p>

                        <p classname="termsandconditiontxt">Eleifend tellus ultricies vel nunc elementum. Eget vitae sed massa sed arcu in pellentesque neque. Congue vitae dictumst luctus facilisi egestas justo, lectus blandit. Justo laoreet a id montes, molestie tempus fringilla nulla. Egestas aliquam integer vitae at tellus, sit et blandit. Placerat aliquam elit sit quis nulla nunc aliquam. Id at orci rhoncus, magna egestas odio sed. Suspendisse fames tortor aliquam, orci morbi. Mauris vitae non fringilla in morbi in et elit suspendisse. Ultricies enim amet sed gravida diam sit risus et. Mattis at nulla ut lectus curabitur. Enim venenatis sagittis, purus aliquet consectetur tincidunt dictum placerat. Etiam ultrices purus feugiat ut faucibus fringilla vel, nunc luctus.</p>

                        <p classname="termsandconditiontxt">Mauris at eget lacus vitae. Tincidunt duis pellentesque urna, neque ut facilisis massa congue. Egestas dapibus diam, augue suspendisse eget. Pharetra sodales neque montes, convallis adipiscing non bibendum malesuada cras. Purus eget maecenas sagittis aliquet nulla nulla quam donec. Lectus malesuada pellentesque proin ac rhoncus tristique turpis ipsum. Et quam tincidunt arcu donec in. Turpis vitae mauris fringilla scelerisque sit. Integer consequat in neque dolor et. Platea laoreet duis pharetra, nunc tellus tempor turpis. Suspendisse fermentum amet donec at. Aliquam at tincidunt lorem eu interdum cras. In ac fringilla curabitur leo. Consequat enim, auctor integer augue. At feugiat elementum convallis nunc ullamcorper risus, proin.</p>

                        <p classname="termsandconditiontxt">Venenatis lectus tincidunt a et aliquam est. Pellentesque augue enim est urna ultrices velit, amet, cursus tellus. Rhoncus vitae etiam proin massa. Aliquam ultricies volutpat amet, eros lacus, sagittis hendrerit semper. Lorem vitae lectus interdum consectetur aliquam viverra mi mauris pulvinar. Cras mattis venenatis dui odio cursus ut etiam et. Nunc sed tortor, habitasse sed id nibh cras pretium. Proin diam, proin lobortis pharetra, ultricies.
                        </p>

                        <p classname="termsandconditiontxt">Sagittis dictumst facilisis aliquam mi amet, sit vitae. Malesuada quis ut tristique nam auctor semper cursus ut. Volutpat eu, cursus ornare cras amet viverra at dolor proin. Arcu sit turpis elementum nam iaculis. Magnis est non id sit adipiscing. Justo, tempor, sagittis metus purus. Eu commodo bibendum varius nec in congue dignissim. Et amet, sed lacinia sed tincidunt. Ullamcorper tortor erat pulvinar non erat amet, quis leo. Lectus pellentesque et praesent et nec faucibus ut pellentesque. Tempor ac aliquam praesent id etiam. Risus, risus sapien sed vivamus viverra porta tellus sem mauris. Libero augue pellentesque lacus, sit convallis auctor.</p>

                        <p classname="termsandconditiontxt">Lacinia morbi neque, ridiculus eget. Malesuada lorem massa nunc in nulla. Dignissim ipsum tortor enim, erat varius id volutpat. Diam erat est libero a proin turpis at nisi ac. Ut consectetur at odio sed magna sollicitudin. Hendrerit vivamus vel eget volutpat laoreet ac praesent enim. Amet egestas congue facilisis cras ornare amet maecenas. Id lorem leo nisl scelerisque. Quisque elit egestas tempus, tincidunt. Commodo quam diam pulvinar aliquet varius viverra velit nulla. Ullamcorper posuere feugiat bibendum arcu. Nulla arcu enim vulputate in tristique ultrices. Ultrices quam integer quis adipiscing enim nunc sit sed pellentesque.</p>

                        <p classname="termsandconditiontxt">Ullamcorper nam aliquam suspendisse sed senectus tristique non massa dolor. Porttitor arcu velit praesent porttitor nunc. Aliquet urna nibh sed ornare ullamcorper nunc dui placerat. Odio interdum nisl vitae sodales ac adipiscing malesuada scelerisque. Varius vitae adipiscing sem rutrum. Proin tincidunt vulputate diam eros. Feugiat suspendisse nisi volutpat neque nunc tortor. Bibendum pharetra id massa etiam ornare vitae nunc facilisis in. Aenean erat feugiat ullamcorper elementum aliquam dictum massa est. Luctus a quam iaculis sed facilisis eu, enim, dui. Leo viverra sed id est neque. Et, enim aliquam magna pellentesque.</p>

                        <p classname="termsandconditiontxt">Magna nisl vehicula bibendum feugiat condimentum duis lobortis sed diam. Eget lacus posuere elit enim, lorem. Leo sed rhoncus sit eleifend morbi. Lorem mi, nunc consequat, gravida eget luctus. Sit faucibus ornare velit ipsum netus. Pulvinar facilisis tortor ut enim. Convallis sit ipsum commodo vitae donec. Varius mus et blandit mauris. Egestas commodo mauris bibendum neque nunc. Ornare convallis fames gravida arcu viverra et posuere id elit. Proin a egestas risus duis iaculis.</p>

                        <p classname="termsandconditiontxt">Id ullamcorper sit dictum pretium vehicula vitae praesent. Feugiat vitae eu vel, lacus. Erat ornare feugiat ac quam ante eu. Tincidunt sit velit leo id non viverra. Sagittis commodo eu diam sem laoreet fermentum turpis. Magnis sed lacus ac venenatis quam adipiscing pulvinar lectus. Ornare facilisis tristique aliquet sed nunc cras velit morbi commodo. Nec consectetur interdum at laoreet libero. Elit, varius gravida eget non viverra nisl consectetur. Pellentesque rutrum nisl nulla gravida accumsan quis nibh nisi.</p>

                        <p classname="termsandconditiontxt">Gravida id sit in id pulvinar in molestie. Nibh sed sit molestie nec hac sagittis. Egestas aliquam aliquet imperdiet id aliquet tristique facilisi cras. Tempor eget turpis at vitae, elementum et cras eros donec. Elementum sed habitasse sed dictum dolor. Turpis in lectus eu porttitor sit malesuada elementum accumsan morbi. Amet sed tellus, enim posuere amet pretium. Non, mi enim posuere suscipit. Imperdiet sit accumsan ut ut odio ac nisl, ac. Id tortor euismod scelerisque neque enim eu sodales ut. Faucibus nisi, blandit id elementum semper accumsan senectus pulvinar. Neque diam metus, odio velit.</p>

                        <p classname="termsandconditiontxt">Bibendum pharetra, accumsan, vulputate et pulvinar maecenas. Augue felis ac tincidunt et in aliquam nisi condimentum lorem. Non massa diam ut aliquam nam. Porttitor et nulla scelerisque enim lectus cursus eleifend suspendisse morbi. Et congue cras egestas pretium odio sed placerat. Quis enim platea sed mattis amet nulla. Vitae rhoncus turpis est etiam bibendum felis. Lectus auctor arcu et egestas at. Amet, ornare vulputate viverra massa pellentesque amet amet at consequat. Laoreet elementum feugiat accumsan egestas egestas. Lacus quis lacus feugiat magna viverra aliquet elementum.</p>

                        <p classname="termsandconditiontxt">Tortor, volutpat enim pellentesque suscipit a hendrerit pretium. Integer congue mauris duis tempor. Quam non arcu morbi scelerisque tincidunt consectetur amet, lobortis condimentum. Amet hendrerit rhoncus elit ut egestas hendrerit etiam. Id interdum risus in urna, aenean aenean pharetra pharetra. Cursus justo mattis adipiscing sem bibendum.</p>

                        <p classname="termsandconditiontxt">Velit cras commodo vivamus dignissim facilisis facilisis et eget eu. Aenean suspendisse amet nunc nulla in in magna. Nulla fermentum sit in consequat turpis vel, id vestibulum sit. Eu et cursus condimentum enim. Sem vitae consequat tortor, elementum tempor, non elit ut. Purus quisque morbi turpis tristique. Quis gravida tortor suspendisse mi mi. Pellentesque pharetra a, nulla sit interdum diam luctus fermentum. Maecenas proin auctor feugiat suspendisse massa. Augue ultrices nec felis faucibus tincidunt ut semper magna. Libero ultrices semper potenti penatibus eget. Tortor eu ac at volutpat. Aenean lectus lectus ut nascetur magna.</p>

                        <p classname="termsandconditiontxt">Malesuada auctor feugiat imperdiet consectetur in ut. Ut feugiat non nec faucibus et sed. Mattis id vel leo blandit. Magna fringilla eu lorem tortor. Quam eu lacus, quis ullamcorper aliquam, vel. A at eu, ut sit consectetur. Nibh enim, risus non tristique risus at varius nisl. Dui eu risus leo at libero metus enim consectetur rhoncus. Ut non sed viverra diam. Est neque erat purus facilisis ridiculus pellentesque sed malesuada arcu. Vulputate justo, egestas gravida lacus, augue sit proin mauris, tincidunt. At nunc sed lacus, tincidunt commodo leo eros est nulla. Lectus sit ut eget faucibus eu.</p>

                        <p classname="termsandconditiontxt">Tortor a turpis mollis venenatis lorem mattis cursus nunc eget. Est, eu turpis id est donec metus pellentesque viverra. Mi risus sed enim at. Nulla proin maecenas porta donec at posuere egestas. Quam volutpat non arcu facilisis risus risus. Quis leo consectetur dui mauris, commodo, mattis. Nec, sed suspendisse laoreet tellus duis amet mattis. Est consequat tincidunt eget vulputate aliquam sed mi at tempus. Purus, viverra ornare vitae amet. Accumsan urna id gravida morbi nullam nunc tincidunt. Consequat id urna arcu lacus. Turpis tortor, eu suscipit facilisis molestie ut interdum risus at.</p>

                        <p classname="termsandconditiontxt">Vulputate ac vitae, ipsum laoreet. Vel quis habitasse elementum, tincidunt leo ornare. Euismod blandit venenatis molestie malesuada id scelerisque rhoncus, in. Nunc porta vestibulum tristique sed nisi. Varius morbi ridiculus lorem enim pellentesque.</p>

                        <p classname="termsandconditiontxt">Justo, dis quam amet habitant turpis. Faucibus risus, odio consectetur sed non. Dis phasellus volutpat augue nullam. Orci duis netus tincidunt nunc sit a tellus. Diam quam elit fermentum ornare metus sit sem.</p>

                        <p classname="termsandconditiontxt">Dui eros, ut consequat turpis tristique tempor, malesuada habitasse arcu. Consequat sed eu mauris sed neque, amet cras. Habitasse mattis facilisis lectus a euismod sit. Vitae est et, congue facilisi. Urna, auctor bibendum convallis placerat nulla ultrices nulla. Viverra risus sed euismod elit vitae. Quisque amet vulputate eget elit, massa euismod orci in pellentesque. Mi nisi, lacus commodo amet lacus aliquet sit sem. Cursus lectus scelerisque libero tincidunt integer interdum cras.</p>

                        <p classname="termsandconditiontxt">Adipiscing ut morbi consectetur purus habitant. Pretium aliquet sem eget parturient purus vitae interdum at. Aliquet urna ac vitae quis duis ut justo massa, gravida. Gravida ut morbi nullam sed faucibus phasellus neque. Odio donec lorem gravida consequat ullamcorper. Elit est mauris elit, amet urna dolor. Et at consectetur ac ultricies malesuada. Vestibulum nec varius dolor, leo eget gravida aliquam nunc. Mattis interdum eu accumsan in sit convallis dui nisl. Sed sagittis morbi magna a ut at in. Sed ante et pulvinar cras tortor at. Neque mauris vitae lorem convallis. Blandit ultricies id sodales sit cursus ullamcorper cras. Pellentesque in metus metus ullamcorper id bibendum. Donec tristique odio nisl leo sed placerat dictumst luctus fringilla.</p>

                        <p classname="termsandconditiontxt">Elementum ornare ut pharetra amet nunc posuere at ipsum. At est sed netus phasellus in arcu nisi tempus sit. Nunc donec arcu egestas sed dictumst elementum quis placerat. Nec viverra in senectus quisque at malesuada dictum semper. Vestibulum faucibus eget facilisis volutpat ac massa tortor elementum a. Ante lacus molestie bibendum vitae lacus enim, velit. Quis elit elementum nunc, et vel dictumst pulvinar laoreet. Malesuada venenatis dictum nam arcu massa. Id ipsum morbi fermentum sed tristique ut risus, fusce. Vitae enim est blandit mi pellentesque neque cras tempus. Sed nunc nunc, neque est nunc quis elit non.</p>

                        <p classname="termsandconditiontxt">Quam ultricies nec condimentum nullam in bibendum sed amet, risus. Vitae sagittis tortor in at sit morbi nulla ipsum, amet. Id massa consequat ut maecenas. Diam posuere neque nibh tristique pellentesque ultricies. Arcu, donec dictumst nisi, blandit arcu feugiat. Duis nisi, dolor purus faucibus feugiat. Aliquam dui id mattis magna aenean elementum eget eu. Nunc quam tortor tortor proin. Et amet feugiat aenean platea vel. Fringilla sed sit lobortis facilisis et. Accumsan nisl pulvinar amet congue aliquam porttitor pellentesque mauris sit. Volutpat tristique pellentesque et at penatibus molestie sollicitudin adipiscing. Enim augue aliquet quis eget.</p>

                        <p classname="termsandconditiontxt">Et semper ipsum, aliquam auctor et. Ornare fermentum quis sit pretium eget vitae fames diam blandit. Diam dolor neque interdum vitae tincidunt vulputate. Mus sed tristique eu, adipiscing dictum turpis. Justo, ullamcorper malesuada nunc, fermentum tempor volutpat quisque. Dignissim risus habitant sit sed non senectus aenean nunc. Id arcu nisl porta diam vulputate purus id. Duis lobortis tempus velit, et. Tempor, nunc lectus nulla vulputate. Lectus sit amet, duis odio. Aliquet eros, sed sed orci habitant in nam eros, egestas. Sed egestas gravida pellentesque odio.</p>

                        <p classname="termsandconditiontxt">In tristique fermentum amet feugiat arcu congue. Risus non eleifend sollicitudin mauris. Faucibus feugiat est, ut amet nunc, at sed vulputate a. Maecenas lectus tortor egestas habitant nibh mi euismod. Adipiscing ac ut ac sed lorem volutpat in blandit aliquet. Elementum pretium amet augue lacus vitae a id nunc nibh. Tortor, condimentum massa sit turpis ipsum ut rhoncus, lorem. Urna habitant nulla luctus volutpat, tincidunt cras odio gravida sapien. Venenatis, a eleifend aliquet blandit accumsan ut. Justo, adipiscing nulla quam aliquet eros fermentum nibh.</p>

                        <p classname="termsandconditiontxt">Sed vivamus ut a consectetur vulputate. Ut ultrices morbi senectus sit. Non ligula tellus eleifend ac amet et fames. Morbi ut viverra velit adipiscing. Aliquam nam sed amet ut enim consectetur platea pulvinar. Lectus vitae aenean amet, ut accumsan. Odio viverra egestas praesent eros. Ut varius nibh cum feugiat id adipiscing id quisque. Porta porttitor vel, pretium condimentum. Dolor eleifend risus libero porttitor neque metus, praesent ma.</p>
                                          
                    </div>
                </div>
            </div>
        </div>    
    </div>
  )
}

export default TermsAndCondition